version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: odoo_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /efs/HLP-ERP-ODOO-17/POSTGRESQL/data:/var/lib/postgresql/data/pgdata
      - /efs/HLP-ERP-ODOO-17/POSTGRESQL/backups:/backup
      - /efs/HLP-ERP-ODOO-17/POSTGRESQL/init:/docker-entrypoint-initdb.d
      - /efs/HLP-ERP-ODOO-17/POSTGRESQL/logs:/var/log/postgresql
    networks:
      - odoo_network
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB' -c 'effective_cache_size=1GB'

  odoo:
    image: odoo:17
    container_name: odoo_app
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      HOST: postgresql
      USER: odoo
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /efs/HLP-ERP-ODOO-17/ODOO/addons:/mnt/extra-addons
      - /efs/HLP-ERP-ODOO-17/ODOO/config:/etc/odoo
      - /efs/HLP-ERP-ODOO-17/ODOO/data:/var/lib/odoo
      - /efs/HLP-ERP-ODOO-17/ODOO/filestore:/var/lib/odoo/filestore
      - /efs/HLP-ERP-ODOO-17/ODOO/logs:/var/log/odoo
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    networks:
      - odoo_network
    command: odoo --config=/etc/odoo/odoo.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: odoo_nginx
    restart: unless-stopped
    depends_on:
      odoo:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /efs/HLP-ERP-ODOO-17/NGINX/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /efs/HLP-ERP-ODOO-17/NGINX/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /efs/HLP-ERP-ODOO-17/NGINX/ssl:/etc/nginx/ssl:ro
      - /efs/HLP-ERP-ODOO-17/NGINX/logs:/var/log/nginx
      - /efs/HLP-ERP-ODOO-17/NGINX/cache:/var/cache/nginx
    networks:
      - odoo_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  odoo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes: {}
  # Nota: Los volúmenes ahora se mapean directamente a /efs/HLP-ERP-ODOO-17/
  # para persistencia en EFS. No necesitamos volúmenes nombrados porque
  # usamos bind mounts directos a la estructura de EFS.

# ESTRUCTURA DEL PROYECTO EN EFS:
# /efs/HLP-ERP-ODOO-17/
# ├── POSTGRESQL/
# │   ├── data/           # Datos de la base de datos
# │   ├── backups/        # Backups automáticos
# │   ├── init/           # Scripts de inicialización
# │   └── logs/           # Logs de PostgreSQL
# ├── ODOO/
# │   ├── addons/         # Addons personalizados
# │   ├── data/           # Datos de Odoo
# │   ├── config/         # Configuración (odoo.conf)
# │   ├── filestore/      # Archivos subidos por usuarios
# │   └── logs/           # Logs de Odoo
# └── NGINX/
#     ├── conf/           # Configuración de Nginx
#     ├── ssl/            # Certificados SSL
#     ├── logs/           # Logs de Nginx
#     └── cache/          # Cache de Nginx
